import { z } from "zod";

export const registrationModeSchema = z.enum(["INDIVIDUAL", "TEAM", "BOTH", "UNDECIDED"]);
export const tentativeStatusSchema = z.enum(["TENTATIVE", "CONFIRMED"]);
export const livestreamStatusSchema = z.enum(["HIDDEN", "TENTATIVE", "LIVE", "ENDED"]);
export const auditionVideoModeSchema = z.enum(["URL", "UPLOAD", "EITHER"]);
export const publicStatusSchema = z.enum(["DRAFT", "SCHEDULED", "PUBLISHED", "ARCHIVED"]);
export const bracketModeSchema = z.enum(["CUSTOM", "SINGLE_ELIMINATION", "OTHER"]);
export const scoreVisibilityModeSchema = z.enum([
  "HIDDEN",
  "AFTER_SUBMIT",
  "AFTER_LOCK",
  "PUBLIC_WHEN_PUBLISHED",
]);
export const tieHandlingModeSchema = z.enum([
  "UNDECIDED",
  "MANUAL_VERDICT",
  "NEEDS_VERDICT",
]);

export const competitionSettingsSchema = z.object({
  competitionName: z.string().min(1),
  competitionSlug: z.string().min(1),
  season: z.string().min(1),
  publicStatus: publicStatusSchema,
  shortDescription: z.string(),
  fullDescription: z.string(),
  landingHeroTitle: z.string(),
  landingHeroHighlight: z.string(),
  landingAudienceText: z.string(),
  landingToolsText: z.string(),
  landingFinalRoundTitle: z.string(),
  finalRoundSprintTitle: z.string(),
  finalRoundSprintDescription: z.string(),
  finalRoundPitchTitle: z.string(),
  finalRoundPitchDescription: z.string(),
  finalRoundVerdictTitle: z.string(),
  finalRoundVerdictDescription: z.string(),
  finalRoundTwistTitle: z.string(),
  finalRoundTwistDescription: z.string(),
  organizerText: z.string(),
  partnerText: z.string(),
  officialContactEmail: z.string(),
  officialContactPhone: z.string(),
  venue: z.string(),
  venueStatus: tentativeStatusSchema,
  eventDate: z.string().nullable(),
  eventDateStatus: tentativeStatusSchema,
  livestreamUrl: z.string(),
  livestreamStatus: livestreamStatusSchema,
  prizeInformation: z.string(),
  rulesDocumentUrl: z.string(),

  registrationMode: registrationModeSchema,
  teamMinSize: z.number().int().min(1),
  teamMaxSize: z.number().int().min(1),
  allowCrossInstitutionTeam: z.boolean(),
  allowTeamInvitations: z.boolean(),
  requireStudentProof: z.boolean(),
  allowParticipantEditAfterSubmit: z.boolean(),
  registrationOpenAt: z.string().nullable(),
  registrationCloseAt: z.string().nullable(),

  submissionOpenAt: z.string().nullable(),
  submissionCloseAt: z.string().nullable(),
  auditionVideoMode: auditionVideoModeSchema,
  auditionVideoRequired: z.boolean(),
  demoUrlRequired: z.boolean(),
  repositoryUrlRequired: z.boolean(),
  documentUploadRequired: z.boolean(),
  promptLogRequired: z.boolean(),
  maxUploadSizeMb: z.number().int().positive(),
  allowedUploadMimeTypes: z.array(z.string()),
  allowSubmissionVersioning: z.boolean(),
  allowEditAfterSubmit: z.boolean(),

  auditionScoreScaleMin: z.number(),
  auditionScoreScaleMax: z.number(),
  auditionScoreStep: z.number(),
  finalScoreScaleMin: z.number(),
  finalScoreScaleMax: z.number(),
  finalScoreStep: z.number(),
  numberOfReviewersPerSubmission: z.number().int().min(1),
  numberOfJudgesPerMatch: z.number().int().min(1),
  blindReviewEnabled: z.boolean(),
  publicScoresEnabled: z.boolean(),
  scoreVisibilityMode: scoreVisibilityModeSchema,
  tieHandlingMode: tieHandlingModeSchema,
  requireReviewComment: z.boolean(),
  requireJudgeComment: z.boolean(),
  judgesMaySeeOthersBeforeSubmit: z.boolean(),

  finalistCount: z.number().int().min(1),
  bracketMode: bracketModeSchema,
  allowByes: z.boolean(),
  currentRoundId: z.string().nullable(),
  currentMatchId: z.string().nullable(),
  sprintDurationSeconds: z.number().int().positive(),
  pitchDurationSeconds: z.number().int().positive(),
  verdictDurationSeconds: z.number().int().positive(),
  twistEnabled: z.boolean(),
  rehearsalCompetitionId: z.string().nullable(),
  bracketLocked: z.boolean(),

  registrationEnabled: z.boolean(),
  submissionEnabled: z.boolean(),
  reviewEnabled: z.boolean(),
  finalistPublicationEnabled: z.boolean(),
  finalScoringEnabled: z.boolean(),
  publicScoreboardEnabled: z.boolean(),
  livestreamEnabled: z.boolean(),
  maintenanceMode: z.boolean(),
  captchaEnabled: z.boolean(),

  primaryLogoAssetId: z.string().nullable(),
  faviconAssetId: z.string().nullable(),
  ogImageAssetId: z.string().nullable(),
  themePrimary: z.string(),
  themeAccent: z.string(),
});

export type CompetitionSettings = z.infer<typeof competitionSettingsSchema>;

export function defaultCompetitionSettings(
  overrides: Partial<CompetitionSettings> = {},
): CompetitionSettings {
  return competitionSettingsSchema.parse({
    competitionName: "AI Arena Vietnam",
    competitionSlug: "prompt-off-vietnam-2026",
    season: "2026",
    publicStatus: "PUBLISHED",
    shortDescription:
      "Sân chơi quốc gia để sinh viên thực hành kỹ năng đặt câu lệnh cùng Google Gemini và Google AI Studio, xây dựng ứng dụng trong 5–10 phút.",
    fullDescription:
      "Cuộc thi ứng dụng AI do Đại học Quốc gia Hà Nội (ĐHQGHN) triển khai, Trường Đại học Công nghệ (VNU-UET) làm đầu mối phối hợp cùng Google tổ chức. Đây là sân chơi công nghệ mở ra cơ hội thực chiến giải quyết các bài toán thực tế thông qua kỹ năng Prompt Engineering trên nền tảng hai công cụ chính thức: **Google Gemini và Google AI Studio**.\n\nHành trình trải nghiệm bắt đầu từ Vòng tuyển chọn trực tuyến nhằm tìm kiếm 8 đội thi xuất sắc nhất bước vào Vòng Chung kết. Tại vòng đấu quyết định này, 8 đội sẽ trực tiếp tranh tài trên sân khấu để tìm ra nhà vô địch.\n\nVòng Chung kết sẽ chính thức diễn ra vào ngày **03/11/2026 tại Hội trường tầng 1, Trung tâm Văn hóa ULIS - Jonathan KS. Choi, ĐHQGHN** (số 144 Xuân Thủy, Cầu Giấy, Hà Nội).",
    landingHeroTitle: "AI Arena",
    landingHeroHighlight: "Vietnam",
    landingAudienceText: "Sinh viên các trường đại học trên toàn quốc",
    landingToolsText: "Google AI Studio và Google Gemini",
    landingFinalRoundTitle: "Thể thức vòng chung kết",
    finalRoundSprintTitle: "The Sprint",
    finalRoundSprintDescription:
      "Hai đội nhận cùng một đề bài, có {thoi_luong} để xây dựng bản thử nghiệm bằng Google Gemini & Google AI Studio — tập trung vào tính khả thi.",
    finalRoundPitchTitle: "The Pitch",
    finalRoundPitchDescription:
      "Thuyết trình {thoi_luong} theo phong cách YC: bài toán, ứng dụng AI và demo sản phẩm.",
    finalRoundVerdictTitle: "The Verdict",
    finalRoundVerdictDescription: "Ban Giám khảo chấm điểm, đánh giá và chọn đội đi tiếp.",
    finalRoundTwistTitle: "On-stage Twist",
    finalRoundTwistDescription:
      "Ban Tổ chức có thể thêm yêu cầu ngay trên sân khấu để thử khả năng ứng biến.",
    organizerText: "Đại học Quốc gia Hà Nội — Trường Đại học Công nghệ (đầu mối phối hợp).",
    partnerText: "Đồng tổ chức: Đại học Quốc gia Hà Nội, Trường Đại học Công nghệ (đầu mối phối hợp) và Google.",
    officialContactEmail: "promptoff@example.edu.vn",
    officialContactPhone: "",
    venue: "Hội trường tầng 1, Trung tâm Văn hóa ULIS - Jonathan KS. Choi, ĐHQGHN",
    venueStatus: "CONFIRMED",
    eventDate: "2026-11-03",
    eventDateStatus: "CONFIRMED",
    livestreamUrl: "",
    livestreamStatus: "HIDDEN",
    prizeInformation: "",
    rulesDocumentUrl: "",
    registrationMode: "BOTH",
    teamMinSize: 2,
    teamMaxSize: 4,
    allowCrossInstitutionTeam: true,
    allowTeamInvitations: true,
    requireStudentProof: false,
    allowParticipantEditAfterSubmit: false,
    registrationOpenAt: "2026-09-15T00:00:00.000Z",
    registrationCloseAt: "2026-10-05T16:59:59.000Z",
    submissionOpenAt: "2026-09-15T00:00:00.000Z",
    submissionCloseAt: "2026-10-05T16:59:59.000Z",
    auditionVideoMode: "URL",
    auditionVideoRequired: false,
    demoUrlRequired: false,
    repositoryUrlRequired: false,
    documentUploadRequired: false,
    promptLogRequired: false,
    maxUploadSizeMb: 25,
    allowedUploadMimeTypes: [
      "application/pdf",
      "image/png",
      "image/jpeg",
      "image/webp",
      "video/mp4",
      "text/plain",
      "application/zip",
    ],
    allowSubmissionVersioning: true,
    allowEditAfterSubmit: false,
    auditionScoreScaleMin: 0,
    auditionScoreScaleMax: 10,
    auditionScoreStep: 0.5,
    finalScoreScaleMin: 0,
    finalScoreScaleMax: 10,
    finalScoreStep: 0.5,
    numberOfReviewersPerSubmission: 2,
    numberOfJudgesPerMatch: 3,
    blindReviewEnabled: true,
    publicScoresEnabled: false,
    scoreVisibilityMode: "PUBLIC_WHEN_PUBLISHED",
    tieHandlingMode: "MANUAL_VERDICT",
    requireReviewComment: true,
    requireJudgeComment: true,
    judgesMaySeeOthersBeforeSubmit: false,
    finalistCount: 8,
    bracketMode: "CUSTOM",
    allowByes: false,
    currentRoundId: null,
    currentMatchId: null,
    sprintDurationSeconds: 300,
    pitchDurationSeconds: 60,
    verdictDurationSeconds: 180,
    twistEnabled: true,
    rehearsalCompetitionId: null,
    bracketLocked: false,
    registrationEnabled: true,
    submissionEnabled: true,
    reviewEnabled: true,
    finalistPublicationEnabled: true,
    finalScoringEnabled: true,
    publicScoreboardEnabled: true,
    livestreamEnabled: false,
    maintenanceMode: false,
    captchaEnabled: false,
    primaryLogoAssetId: null,
    faviconAssetId: null,
    ogImageAssetId: null,
    themePrimary: "#0B1F3A",
    themeAccent: "#C9A227",
    ...overrides,
  });
}

export function parseCompetitionSettings(value: unknown): CompetitionSettings {
  const record = typeof value === "object" && value !== null ? (value as Record<string, unknown>) : {};
  return competitionSettingsSchema.parse({ ...defaultCompetitionSettings(), ...record });
}
