export const LANDING_ASSETS = {
  heroHeadline: "/landing/ai-arena-vn.png",
  swagKit: "/landing/swag-kit.png",
  bgTexture: "/landing/imgBgTexture.png",
  badgeTech: "/landing/imgBadgeTech.png",
  badgeRed: "/landing/imgBadgeRed.png",
  badgeYellow: "/landing/imgBadgeYellow.png",
  overlayCard: "/landing/imgOverlayCard.png",
  overlaySvg: "/landing/imgOverlaySvg.svg",
  logoVnu: "/landing/imgLogoVnu.png",
  logoVnuLg: "/landing/imgLogoVnuLg.png",
  logoGoogle: "/landing/imgLogoGoogle.png",
  logoUet: "/landing/imgLogoUet.png",
  iconSprint: "/landing/imgIconSprint.png",
  iconPitch: "/landing/imgIconPitch.png",
  iconVerdict: "/landing/imgIconVerdict.png",
  iconTwist: "/landing/imgIconTwist.png",
  chevron: "/landing/imgChevron.png",
} as const;
